source "https://rubygems.org"

ruby "~> 3.4.0"

gem "rails", "~> 8.1.0"

# Database
gem "pg", "~> 1.5"

# Web server
gem "puma", ">= 5.0"

# Asset pipeline
gem "propshaft"

# JavaScript
gem "importmap-rails"

# Hotwire
gem "turbo-rails"
gem "stimulus-rails"

# Authentication
gem "bcrypt", "~> 3.1.7"

# HTTP client for API integrations
gem "faraday"

# Pagination
gem "kaminari"

# JSON
gem "jbuilder"

# Caching
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Boot speed
gem "bootsnap", require: false

# Timezone data for Windows
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "rantly"
end
